" ┌──────────────────────────┐
" │                          │
" │  Addison Amiri's .vimrc  │
" │                          │
" └──────────────────────────┘

" General─────────────────────

set modelines=0               " turn off modelines for security purposes
filetype plugin indent on     " turn on a bunch of stuff
set nocompatible              " turn off vi compatibility
let g:molokai_original = 0    " use original monokai colorscheme to match terminal colors
colorscheme molokai           " molokai colorscheme


" Let's Begin─────────────────

set hidden                    " allow for hiding modified buffers
set encoding=utf-8
set backspace=indent,eol,start
set noswapfile
set ruler
syntax on
set autoindent smartindent
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2
set cpoptions+=$
set wildmenu
set number


" Remaps─────────────────

" remap ; to : so you don't have to hold shift
map ; :
" escape on ., so you roll your fingers to insert a command (.,;)
imap ., <Esc>
" map leader
let mapleader = "-"
" tree
nmap <leader>t :NERDTree<CR>
" buffers
nmap <leader>b :ls<CR>:b 
" shell
nmap <leader>s :ConqueTerm zsh<CR>
" matrix
nmap <leader>m :Matrix<CR>
