" ┌──────────────────────────┐
" │                          │
" │  Addison Amiri's .vimrc  │
" │                          │
" └──────────────────────────┘

" General─────────────────────

set modelines=0               " turn off modelines for security purposes
execute pathogen#infect()
filetype plugin indent on     " turn on a bunch of stuff
set nocompatible              " turn off vi compatibility
"let g:molokai_original = 0    " use original monokai colorscheme to match terminal colors
"colorscheme molokai           " molokai colorscheme
colorscheme cterm


" Let's Begin─────────────────

set hidden                    " allow for hiding modified buffers
set encoding=utf-8
set backspace=indent,eol,start
set noswapfile
set ruler
syntax on
set autoindent smartindent
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2
set cpoptions+=$
set wildmenu
set number
set laststatus=2              " always show statusbar


" Statusline──────────────────

set statusline=%t       "tail of the filename
set statusline+=\ [\ %{strlen(&fenc)?&fenc:'none'}\ , "file encoding
set statusline+=\ %{&ff}\ ] "file format
set statusline+=\ %h      "help file flag
set statusline+=\ %m      "modified flag
set statusline+=%#warningmsg#
set statusline+=\ %r      "read only flag
set statusline+=%*
set statusline+=\ %y      "filetype
set statusline+=%#warningmsg#
set statusline+=\ %{SyntasticStatuslineFlag()}
set statusline+=%*
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l\ /\ %L   "cursor line/total lines
set statusline+=\ %P    "percent through file


" Highlights──────────────────

let java_mark_braces_in_parens_as_errors=1
let java_highlight_java_lang_ids=1
let java_highlight_functions="style"


" Syntastic───────────────────

let g:syntastic_auto_loc_list=1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_auto_jump = 1

" Remaps──────────────────────

" remap ; to : so you don't have to hold shift
map ; :
" escape on ., so you roll your fingers to insert a command (.,;)
imap ., <Esc>
" map leader
let mapleader = "-"
" tree
nmap <leader>t :NERDTree<CR>
" buffers
nmap <leader>b :ls!<CR>:b 
" shell
nmap <leader>s :ConqueTerm zsh<CR>
" matrix
nmap <leader>m :Matrix<CR>
" indent
nmap <leader>i gg=G``
" whitespace
nmap <leader>w :%s/\s\+$//g<CR>``
