#! /usr/bin/zsh

sxhkd &

bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X

bspc config border_width          1
bspc config window_gap            20
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# extras
urxvtd -q -f -o
#compton -b
monitor
