#! /usr/bin/zsh

if [[ -e ~/.config ]]; then
  if [[ ! ( -d ~/.config ) ]]; then
    echo "There's a ~/.config and it's not a directory..."; exit 1
  else
    if [[ -e ~/.config/bspwm ]]; then
      if [[ ! ( -d ~/.config/bspwm ) ]]; then
        echo "There's a ~/.config/bspwm and it's not a directory..."; exit 1
      else
        echo "There's already a bspwm in ~/.config/\nIt has been renamed bspwm.old"
        mv ~/.config/bspwm ~/.config/bspwm.old
      fi
    fi
  fi
else
  mkdir -p ~/.config
fi

mypath=$(exec 2>/dev/null;cd $(dirname $0);unset PWD;/usr/bin/pwd||/bin/pwd||pwd)
ln -s $mypath/bspwm ~/.config/bspwm
