#!/usr/bin/zsh

mypath=$(exec 2>/dev/null;cd $(dirname $0);unset PWD;/usr/bin/pwd||/bin/pwd||pwd)

sxhkd &
$mypath/panel_loop &
$mypath/monitor

bspc config focused_border_color    #88ff88
bspc config active_border_color     #000000
bspc config normal_border_color     #000000
bspc config presel_border_color     #66cccc
bspc config urgent_border_color     #b87457
bspc config border_width            1
bspc config window_gap              20
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config auto_cancel             true

# extras
urxvtd -q -f -o
compton -cCzfb -m .9 --shadow-green .1 --use-ewmh-active-win --backend glx
