#! /bin/sh

export PANEL_FIFO=/tmp/panel_fifo
export PANEL_HEIGHT=18

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
conky > "$PANEL_FIFO" &

mypath=$(exec 2>/dev/null;cd $(dirname $0);unset PWD;/usr/bin/pwd||/bin/pwd||pwd)

case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | ${mypath}/panel_bar | bar &
        ;;
    dzen2)
        . ${mypath}/panel_colors
        FONT_FAMILY='gohufont'
        FONT_SIZE=9
        cat "$PANEL_FIFO" | ${mypath}/panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
        ;;
esac

wait
