#! /usr/bin/zsh

if [[ -e ~/.config ]] ; then
  if [[ ! ( -d ~/.config ) ]] ; then
    echo "There's a ~/.config and it's not a directory..."; exit 1
  else
    if [[ -e ~/.config/sxhkd ]] ; then
      if [[ ! ( -d ~/.config/sxhkd ) ]] ; then
        echo "There's a ~/.config/sxhkd and it's not a directory..."; exit 1
      else
        echo "There's already a sxhkd in ~/.config/\nIt has been renamed sxhkd.old"
        mv ~/.config/sxhkd ~/.config/sxhkd.old
      fi
    fi
  fi
else
  mkdir -p ~/.config
fi

mypath=$(exec 2>/dev/null;cd $(dirname $0);unset PWD;/usr/bin/pwd||/bin/pwd||pwd)
ln -s $mypath/sxhkd ~/.config/sxhkd
