#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Xresources
xrdb -load ~/.Xresources
# to load a colorscheme from a seperate file use this
#xrdb -override ~/.colorscheme

# Mouse cursor
xsetroot -cursor_name left_ptr

# BSPWM
exec bspwm
