# ┌──────────────────────────┐
# │                          │
# │  Addison Amiri's .zshrc  │
# │                          │
# └──────────────────────────┘

# Created By compinstall──────

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' format 'completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd directory
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:]}={[:upper:]} r:|[._-/]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=1
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' prompt '%e posssible corrections'
zstyle ':completion:*' select-prompt %B%SScrolling active: current selection at %l%s%b
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/addison/.zshrc'
autoload -Uz compinit
autoload -U zmv
compinit


# Created By zsh-newuser-install──

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt notify
unsetopt appendhistory autocd beep nomatch
bindkey -v


# Variables───────────────────

# xdg directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DESKTOP_DIR="$HOME"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_TEMPLATES_DIR="$HOME/templates"
export XDG_PUBLICSHARE_DIR="$HOME/public"
export XDG_DOCUMENTS_DIR="$HOME/text"
export XDG_MUSIC_DIR="$HOME/sound"
export XDG_PICTURES_DIR="$HOME/images"
export XDG_VIDEOS_DIR="$HOME/video"

# other shit
export BROWSER="firefox"
export EDITOR="vim"
export SHELL="/usr/bin/zsh"
export PATH=$PATH:/home/addison/bin/


# Prompt Config───────────────

autoload -U colors && colors
local return_code='%(?..↳%?)'

PROMPT="%{$fg[red]%}${return_code}%{$reset_color%}> "
RPROMPT="%1d"


# Aliases─────────────────────

alias grep="grep --color=auto"    # color grep
alias more="less"                 # less is more
alias df="df -h"                  # human readable
alias du="du -c -h"               # produce a total and human readable
alias mkdir="mkdir -p -v"         # make parents verbosely
alias ping="ping -c 5"            # 5 times
alias dmesg="dmesg -HL"           # human readable in color
alias mplayer="mplayer -msgcolor" # color mplayer output

alias du1="du --max-depth=1"      # stop du 1 dir deep
alias hist="history | grep"       # search zsh history
alias openports="ss --all --numeric --processes --ipv4 --ipv6"  # list open ports
alias td="transmission-daemon"    # transmission daemon
alias trc="transmission-remote-cli" # transmission cli


# Privileged Access───────────

if [[ $UID -ne 0 ]]; then
  alias sudo="sudo "
  alias scat="sudo cat"
  alias svim="sudo vim"
  alias root="sudo -s"
  alias reboot="sudo systemctl reboot"
  alias poweroff="sudo systemctl poweroff"
  alias shutdown="sudo shutdown now"
  alias netctl="sudo netctl"
fi


# Ls──────────────────────────

alias ls="ls -hF --color=auto"
alias lr="ls -R"
alias ll="ls -l"
alias la="ll -A"
alias lx="ll -BX"
alias lz="ll -rS"
alias lt="ll -rt"


# Safety Features─────────────

alias cp="cp -i"
alias mv="mv -i"
alias rm="timeout 3 rm -Iv --one-file-system"
alias ln="ln -i"
alias chown="chown --preserve-root"
alias chmod="chmod --preserve-root"
alias chgrp="chgrp --preselve-root"
alias cls="echo -ne '\033c'"


# Package Manager Stuff───────

alias pac="/usr/bin/pacaur -S"        # default action
alias pacu="/usr/bin/pacaur -Syu"     # [u]pdate
alias pacr="/usr/bin/pacaur -Rs"      # [r]emove
alias pacs="/usr/bin/pacaur -Ss --votes"      # [s]earch
alias paci="/usr/bin/pacaur -Si"      # [i]nfo
alias pacii="/usr/bin/pacaur -Sii"    # [i]ntense [i]nfo


# Directory Bookmarks─────────

alias dl="cd /home/addison/downloads"
alias dev="cd /home/addison/development"
alias dot="cd /home/addison/development/repos/dotfiles"
alias music="cd /home/addison/sound/music"
alias movies="cd /home/addison/video/movies"
alias tv="cd /home/addison/video/tv"
alias school="cd /home/addison/school/14spring"
alias apph="cd /home/addison/school/14spring/apph_1040_a"
alias cs="cd /home/addison/school/14spring/cs_1332_a1"
alias cst="cd /home/addison/school/14spring/cs_1801_b"
alias hts="cd /home/addison/school/14spring/hts_3061_a"
alias phil="cd /home/addison/school/14spring/phil_3127_bh"


# Functions───────────────────

function wallpaper () {
if [[ ($1 == 1) || (-z $(xrandr | grep " connected" | grep VGA)) ]]; then
  find ~/images/wallpaper -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z | xargs -0 feh --no-fehbg --bg-fill
else
  find ~/images/wallpaper -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n2 -z | xargs -0 feh --no-fehbg --bg-fill
fi
}

function monitor () {
if [[ ($1 == 1) || (-z $(xrandr | grep " connected" | grep VGA)) ]]; then
  xrandr --output VGA1 --off
  bspc monitor -d I II III IV V VI VII VIII IX X
  wallpaper 1
  bspc config top_padding 18
else
  xrandr --output VGA1 --auto --pos 0x0 --output LVDS1 --auto --pos 1920x280 # 280=1080-800
  bspc monitor VGA1 -d I II III IV V
  bspc monitor LVDS1 -d VI VII VIII IX X
  wallpaper 2
  bspc config -m LVDS1 top_padding 0
  bspc config -m VGA1 top_padding 18
fi
bspc config window_gap 20
}

function net () {
if [[ -z $1 ]]; then
  sudo wifi-menu
else
  case "$1" in
    dads)
      sudo netctl start dads_house
      ;;
    7)
      sudo netctl start 7_coffee
      ;;
    matts)
      sudo netctl start matts_house
      ;;
    starbucks)
      sudo netctl start starbucks
      ;;
    tech)
      sudo netctl start tech
      ;;
    eth)
      sudo dhcpcd enp0s25
      ;;
    off)
      sudo netctl stop-all
      ;;
    *)
      sudo wifi-menu
      ;;
  esac
fi
}
